using System;
using System.Windows.Forms;
using budget.Database;

namespace BudgetTracker
{
    // Delegate declaration
    // Defines a method signature to be used for the BudgetSaved event.
    public delegate void BudgetSavedHandler(string month, string year, decimal limit);

    public partial class Budget : Form
    {
        // Event based on the delegate
        // Allows other parts of the program to subscribe to budget save notifications.
        public event BudgetSavedHandler BudgetSaved;

        public Budget()
        {
            InitializeComponent(); // Standard method to initialize the form and its controls.
        }

        private void Budget_Load(object sender, EventArgs e)
        {
            // Initialize database structure/tables if not already present.
            Budgetdb.InitializeDatabase();

            // Populate the combo box with month names using culture info.
            cmbMonth.Items.AddRange(System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.MonthNames);
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            // Get values from user input fields
            string month = cmbMonth.Text;
            string year = txtYear.Text.Trim();
            string limitText = txtLimit.Text.Trim();

            // Basic validation: ensure no field is left empty.
            if (string.IsNullOrEmpty(month) || string.IsNullOrEmpty(year) || string.IsNullOrEmpty(limitText))
            {
                MessageBox.Show("All fields are required.", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Ensure limit is a valid decimal number.
            if (!decimal.TryParse(limitText, out decimal limit))
            {
                MessageBox.Show("Invalid limit amount.", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Attempt to save data to the database.
            bool success = Budgetdb.SaveMonthlyBudget(month, year, limit);

            // Display result to the user using a status label.
            lblStatus.Text = success ? "✅ Budget saved successfully!" : "❌ Failed to save budget.";

            // If saved successfully, notify subscribers using the BudgetSaved event.
            if (success)
            {
                BudgetSaved?.Invoke(month, year, limit); // ➤ Null-conditional to avoid exception if no subscribers.
            }
        }

        // Placeholder for label click event – currently unused but auto-generated by Visual Studio designer.
        private void lblStatus_Click(object sender, EventArgs e)
        {
        }

        // Placeholder for dropdown event – could be used to react when user selects a month.
        private void cmbMonth_SelectedIndexChanged(object sender, EventArgs e)
        {
        }

        // Placeholder for label click event – currently unused.
        private void lblMonth_Click(object sender, EventArgs e)
        {
        }
    }
}
